### PR TITLE
FetchWithRetries middleware

### PR DESCRIPTION
**Pull request by mario-jerkovic**
Here is my implementation of fetchWithRetries middleware. If there is some code that need to be changes I am opened to advices 👍 .

Also I've updated README to reflect the new changes.

### CODE REVIEW

**Comment by nodkz** [comment]
Brilliant!  👍 👍 👍

**Comment by mario-jerkovic** [comment]
No problem, and thank you for this great lib.

**Comment by mario-jerkovic** [comment]
One bug is in this PR,  line 15 in retry.js . It should be :
```js
 if (res.status < 200 || res.status > 300 || !res.status.ok ) { ... }
```

**Comment by nodkz** [comment]
Yep, without tests OSS projects is very unpredictable and tedious ))
But I have not good experience in it. And have not enough time to start it from scratch.

BTW, I released 1.0.3 with forceFetch and thunk for retries. In example add simple exponential function. You may allow to user press button for force retry.

**Comment by mario-jerkovic** [comment]
Yes, will take a look at it (testing), and PM you if I make some progress :+1:

**Pull request merged**
